<a href="https://colab.research.google.com/github/Evelynmaezj/ANALITICA-DE-DATOS/blob/main/Actividad%203.3/Actividad_3_3_Extracci%C3%B3n_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#EXTRACCIÓN DE DATOS INMUEBLES

In [2]:
#Librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Cargar archivos csv o xlsx desde equipo
from google.colab import files
files.upload()

In [4]:
#Carga archivo .xlsx sin indice
df=pd.read_excel('Inmuebles.xlsx')
df

,Esta es una base de datos que describe las operaciones inmobiliarias de una empresa,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,1,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291,2133903,2004-06-19 00:00:00,Carmen
2,2,2004-01-01 00:00:00,Local,Venta,Girona,185,1945424,2004-04-19 00:00:00,Pedro
3,3,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82,NaN,2004-11-08 00:00:00,Joaquín
4,4,2004-01-02 00:00:00,Parking,Alquiler,Girona,285,NaN,2004-04-27 00:00:00,Jesús
...,...,...,...,...,...,...,...,...,...
3333,3333,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221,1450644,NaN,NaN
3334,3334,2007-04-29 00:00:00,Piso,Alquiler,Girona,55,454080,NaN,NaN
3335,3335,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78,740688,NaN,NaN
3336,3336,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88,397408,NaN,NaN
3337,3337,2007-04-30 00:00:00,Parking,Venta,Lleida,254,2140712,NaN,NaN

In [5]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3338 entries, 0 to 3337
Data columns (total 9 columns):
 #   Column                                                                               Non-Null Count  Dtype
---  ------                                                                               --------------  -----
 0   Esta es una base de datos que describe las operaciones inmobiliarias de una empresa  3338 non-null   object
 1   Unnamed: 1                                                                           3338 non-null   object
 2   Unnamed: 2                                                                           3338 non-null   object
 3   Unnamed: 3                                                                           3338 non-null   object
 4   Unnamed: 4                                                                           3338 non-null   object
 5   Unnamed: 5                                                                           3336 non-null   object
 6   Unnamed: 6                                                                           3336 non-null   object
 7   Unnamed: 7                                                                           2760 non-null   object
 8   Unnamed: 8                                                                           2760 non-null   object
dtypes: object(9)
memory usage: 234.8+ KB

In [6]:
#Exploración inmediata imprimiendo los 5 primeros registros del df
df.head()

,Esta es una base de datos que describe las operaciones inmobiliarias de una empresa,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,1,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291,2133903,2004-06-19 00:00:00,Carmen
2,2,2004-01-01 00:00:00,Local,Venta,Girona,185,1945424,2004-04-19 00:00:00,Pedro
3,3,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82,NaN,2004-11-08 00:00:00,Joaquín
4,4,2004-01-02 00:00:00,Parking,Alquiler,Girona,285,NaN,2004-04-27 00:00:00,Jesús

##a) Eliminar la primera fila
Ya que esta fila no contiene información relevante, vuelve a leer el data frame y se agrega con una coma skiprows para inficar el número de fila iniciando por 1

In [54]:
df=pd.read_excel('Inmuebles.xlsx', skiprows=1)
df

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
2,3,2004-01-01,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08,Joaquín
3,4,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
4,5,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
...,...,...,...,...,...,...,...,...,...
3332,3333,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3333,3334,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT,NaN
3334,3335,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT,NaN
3335,3336,2007-04-30,Piso,Alquiler,Barcelona,88.0,397408.0,NaT,NaN
3336,3337,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

##a) Eliminar la columnas
Por medio de drop, usando:

*   axis=0 para filas
*   axis=1 para  columnas

Se eliminaran la columna "0" y "Referencia"

In [55]:
#Eliminar columnas innecesarias
#axis = 1 para columnas
#axis = 0 para filas
#df=pd.read_excel('Inmuebles.xlsx',skiprows=1, index_col=1)
df = df.drop(['Referencia'], axis=1)
df

,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
2,2004-01-01,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08,Joaquín
3,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
4,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3333,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT,NaN
3334,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT,NaN
3335,2007-04-30,Piso,Alquiler,Barcelona,88.0,397408.0,NaT,NaN
3336,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

##b) Filtro de registros "Fecha_Alta"
Fecha Alta : igual a 2007-04-29 00:00:00 y a 2004-01-02 00:00:00

In [56]:
filtro1 = df[(df['Fecha_Alta'] == '2007-04-29') | (df['Fecha_Alta'] =='2004-01-02')]
filtro1

,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
3,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
4,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
3331,2007-04-29,Oficina,Venta,Lleida,190.0,1031320.0,NaT,NaN
3332,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3333,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT,NaN

##c) Filtro de registros en tipo
Todos los registros de “ Tipo: parking, local, industrial y piso”

In [57]:
filtro2 = df[(df['Tipo'] == 'Parking') |
             (df['Tipo'] == 'Local') |
             (df['Tipo'] == 'Suelo') |
             (df['Tipo'] =='Piso')]
filtro2

,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
3,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
4,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
6,2004-01-03,Parking,Alquiler,Tarragona,NaN,406686.0,2004-06-07,Pedro
...,...,...,...,...,...,...,...,...
3330,2007-04-27,Local,Venta,Girona,110.0,845790.0,NaT,NaN
3333,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT,NaN
3334,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT,NaN
3335,2007-04-30,Piso,Alquiler,Barcelona,88.0,397408.0,NaT,NaN
3336,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

##d) Filtro de Provincia **Y** Superficie
Todos los registros con “Provincia” igual a “Girona” y con “Superficie” mayor a “100”

In [36]:
filtro3 = df[(df['Provincia'] == 'Girona') &
             (df['Superficie'] > 100)]
filtro3

,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
3,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
5,2004-01-03,Industrial,Alquiler,Girona,131.0,953156.0,2004-09-05,Pedro
7,2004-01-03,Oficina,Venta,Girona,235.0,2158475.0,2004-10-31,Jesús
10,2004-01-04,Oficina,Alquiler,Girona,124.0,627068.0,2004-10-28,Pedro
...,...,...,...,...,...,...,...,...
3299,2007-04-12,Local,Alquiler,Girona,156.0,881868.0,NaT,NaN
3303,2007-04-12,Piso,Venta,Girona,128.0,1270400.0,NaT,NaN
3306,2007-04-14,Parking,Venta,Girona,221.0,1533077.0,NaT,NaN
3316,2007-04-20,Casa,Venta,Girona,247.0,1804088.0,NaT,NaN
3330,2007-04-27,Local,Venta,Girona,110.0,845790.0,NaT,NaN

##e) Filtro Precio Venta **O** Vendedor
Todos los registros con “Precio Venta: mayor a 1000,000” o “vendedor” igual a “Carmen o Joaquin”

In [38]:
filtro4 = df[(df['Precio Venta'] > 1000000) |
             (df['Vendedor'] =='Carmen') |
             (df['Vendedor'] =='Joaquin')]
filtro4

,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
7,2004-01-03,Oficina,Venta,Girona,235.0,2158475.0,2004-10-31,Jesús
8,2004-01-04,Piso,Alquiler,Lleida,108.0,1024380.0,2004-12-28,Jesús
9,2004-01-04,Parking,Venta,Lleida,299.0,2042768.0,2004-10-06,Joaquín
...,...,...,...,...,...,...,...,...
3325,2007-04-25,Industrial,Alquiler,Barcelona,296.0,2078216.0,NaT,NaN
3328,2007-04-26,Piso,Venta,Barcelona,264.0,2517504.0,NaT,NaN
3331,2007-04-29,Oficina,Venta,Lleida,190.0,1031320.0,NaT,NaN
3332,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3336,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

##f) Filtro negación de Provincia
Todos los registros que no sean de “Provincia : Barcelona“

In [41]:
filtro5 = df[~(df['Provincia'] == 'Barcelona')]
filtro5

,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
2,2004-01-01,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08,Joaquín
3,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
4,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
...,...,...,...,...,...,...,...,...
3331,2007-04-29,Oficina,Venta,Lleida,190.0,1031320.0,NaT,NaN
3332,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3333,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT,NaN
3334,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT,NaN
3336,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

##g) Filtro negación de Operación y Tipo
Todos los registros que no sean de “Operación: alquiler “ ni “Tipo: oficina“

In [44]:
filtro6 = df[~(df['Operación'] == 'Alquiler') &
               ~(df['Tipo'] == 'Oficina')]
filtro6

,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
4,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
9,2004-01-04,Parking,Venta,Lleida,299.0,2042768.0,2004-10-06,Joaquín
11,2004-01-04,Industrial,Venta,Girona,187.0,999328.0,2004-04-05,Carmen
12,2004-01-04,Parking,Venta,Barcelona,NaN,2937300.0,2004-11-04,Jesús
...,...,...,...,...,...,...,...,...
3328,2007-04-26,Piso,Venta,Barcelona,264.0,2517504.0,NaT,NaN
3329,2007-04-27,Parking,Venta,Barcelona,88.0,612568.0,NaT,NaN
3330,2007-04-27,Local,Venta,Girona,110.0,845790.0,NaT,NaN
3334,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT,NaN
3336,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

##Guardado de filtros y archivo en CSV

In [ ]:
#Convertir archivo filtrado a CSV
filtro1.to_csv("Entregable1.csv")
filtro2.to_csv("Entregable2.csv")
filtro3.to_csv("Entregable3.csv")
filtro4.to_csv("Entregable4.csv")
filtro5.to_csv("Entregable5.csv")
filtro6.to_csv("Entregable6.csv")

In [ ]:
#descardar archivo filtrado en csv
from google.colab import files


files.download("Entregable1.csv")